### ISSUE TITLE
Error when command dronekit-sitl copter

### ISSUE THREAD

**Issue by khoa2607** [dronekit/dronekit-sitl#116]
Hello everyone,

I'm TOTALLY new here. 
I was trying to call the command "dronekit-sitl copter", however, it shows error and it can't connect.

This is the error:
Traceback (most recent call last):
  File "/usr/local/bin/dronekit-sitl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: future==0.15.2

Please help! It was working fine, but I tried to upgrade Mavproxy or something :(. Then, the error shows up. Thank you so so so  much! This is also my first time posting on Github too.

**Comment by nthgol** [comment]
are you sure you followed the installation instructions? first dronekit, then dronekit-sitl
