### ISSUE TITLE
sitl issue on raspberry pi

### ISSUE THREAD

**Issue by sameenashaikh29** [dronekit/dronekit-sitl#119]
This is the error i am getting when i try to run a python code on my raspberry pi interfacing the pixhawk through serial pins. Any help appreciated.

pi@raspberrypi:~ $ python hello.py
Start simulator (SITL)
Starting copter simulator (SITL)
SITL already Downloaded and Extracted.
Ready to boot.
Failed to run (/home/pi/.dronekit/sitl/copter-3.3/apm)
Traceback (most recent call last):
  File "hello.py", line 3, in <module>
    sitl = dronekit_sitl.start_default()
  File "/home/pi/.local/lib/python2.7/site-packages/dronekit_sitl/__init__.py", line 454, in start_default
    sitl.launch(sitl_args, await_ready=True, restart=True)
  File "/home/pi/.local/lib/python2.7/site-packages/dronekit_sitl/__init__.py", line 253, in launch
    caps = ArdupilotCapabilities(self.path)
  File "/home/pi/.local/lib/python2.7/site-packages/dronekit_sitl/__init__.py", line 165, in __init__
    self.has_defaults_path = "--defaults path" in helptext
UnboundLocalError: local variable 'helptext' referenced before assignment
pi@raspberrypi:~ $

**Comment by peterbarker** [comment]
On Mon, 18 Dec 2017, sameenashaikh29 wrote:

> This is the error i am getting when i try to run a python code on my
> raspberry pi interfacing the pixhawk through serial pins. Any help
> appreciated.

Sorry, you'll have to compile your own copy of SITL for ARM.

> Failed to run (/home/pi/.dronekit/sitl/copter-3.3/apm)

The file is probably the wrong format - x86 vs ARM

> UnboundLocalError: local variable 'helptext' referenced before assignment

I've pushed in a fix for this.
