### ISSUE TITLE
Timeout on <Calibrating barometer>

### ISSUE THREAD

**Issue by DylanVanAssche** [dronekit/dronekit-sitl#124]
I'm trying to get the quick start example (http://python.dronekit.io/guide/quick_start.html) working but every time I want to start an SITL copter it fails due a timeout when calibrating the barometer.

Seems like a bug? Or is it my configuration?

**Code:**
```
print ("Start simulator (SITL)")
import dronekit_sitl
sitl = dronekit_sitl.start_default()
connection_string = sitl.connection_string()

# Import DroneKit-Python
from dronekit import connect, VehicleMode

# Connect to the Vehicle.
#print("Connecting to vehicle on: %s" % (connection_string,))
print("Connecting to vehicle on: {0}".format(connection_string))
vehicle = connect(connection_string, wait_ready=True,  heartbeat_timeout=180)

# Get some vehicle attributes (state)
print("GPS {0}".format(vehicle.gps_0))
print("Battery {0}".format(vehicle.battery))
print("Heartbeat {0}".format(vehicle.last_heartbeat))
print("Armable {0}".format(vehicle.is_armable))
print("System state {0}".format(vehicle.system_status.state))
print("Mode {0}".format(vehicle.mode.name ))

# Close vehicle object before exiting script
vehicle.close()

# Shut down simulator
sitl.stop()
print("Completed")
```

**Output:**
```
Start simulator (SITL)
Starting copter simulator (SITL)
SITL already Downloaded and Extracted.
Ready to boot.
Connecting to vehicle on: tcp:127.0.0.1:5760
>>> APM:Copter V3.3 (d6053245)
>>> Frame: QUAD
>>> Calibrating barometer
Traceback (most recent call last):
  File "drone.py", line 12, in <module>
    vehicle = connect(connection_string, wait_ready=True,  heartbeat_timeout=180)
  File "/usr/lib/python3.4/site-packages/dronekit/__init__.py", line 2849, in connect
    vehicle.wait_ready(True)
  File "/usr/lib/python3.4/site-packages/dronekit/__init__.py", line 2199, in wait_ready
    timeout)
dronekit.APIException: wait_ready experienced a timeout after 30 seconds.
```

**Environment:**

- OpenSUSE Leap 42.3 / Xubuntu 14.04 LTS
- Python 3.4
- Intel CPU x64 / AMD CPU x64

Am I doing something wrong? I read that the SITL images are only for x86 architecture, but I run the x64 architecture...

**Comment by DylanVanAssche** [comment]
Hmmm Python 3 isn't supported, I missed that in the Quick Start guide.

**Comment by sarthak268** [comment]
Please add this to the README also, it would be helpful.

**Comment by Vaibhavg133** [comment]
I'm also facing the same issue in python2.7 please hel
![Screenshot from 2019-10-04 02-37-35](https://user-images.githubusercontent.com/25547593/66164311-03fa0580-e650-11e9-9547-a195dcd43a75.png)
p
