### ISSUE TITLE
dronekit-sitl

### ISSUE THREAD

**Issue by sanjay219** [dronekit/dronekit-sitl#132]
i am using cigwin in windows 10. whenever i used the following command, it shows error
$ pip2 install dronekit-sitl 

Collecting dronekit-sitl
  Using cached https://files.pythonhosted.org/packages/0c/32/73a2aee4936e59e912407a0a5974da24f21dcc8fc66c6cd65144c1dd93df/dronekit_sitl-3.3.0-py2-none-any.whl
Requirement already satisfied: dronekit>=2.0.0b6 in /usr/lib/python2.7/site-packages (from dronekit-sitl) (2.9.2)
Collecting six>=1.10 (from dronekit-sitl)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting psutil>=3.0 (from dronekit-sitl)
  Using cached https://files.pythonhosted.org/packages/2f/b8/11ec5006d2ec2998cb68349b8d1317c24c284cf918ecd6729739388e4c56/psutil-5.6.1.tar.gz
    Complete output from command python setup.py egg_info:
    platform cygwin is not supported

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-t_Fj1v/psutil/

**Comment by AntonioDiBella** [comment]
Hello friends,
I have this problem with the dronekit execution. can someone help me?

pi@raspberrypi:~ $ dronekit-sitl copter
os: linux, apm: copter, release: stable
Downloading SITL from http://dronekit-assets.s3.amazonaws.com/sitl/copter/sitl-linux-copter-3.3.tar.gz
Download Complete.
Payload Extracted.
Ready to boot.
Traceback (most recent call last):
  File "/home/pi/.local/bin/dronekit-sitl", line 10, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python2.7/site-packages/dronekit_sitl/__init__.py", line 601, in main
    sitl.launch(args, verbose=True)
  File "/home/pi/.local/lib/python2.7/site-packages/dronekit_sitl/__init__.py", line 251, in launch
    caps = ArdupilotCapabilities(self.path)
  File "/home/pi/.local/lib/python2.7/site-packages/dronekit_sitl/__init__.py", line 160, in __init__
    process = subprocess.Popen([path, '--help'], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
