### ISSUE TITLE
DRONEKIT ON RPi3

### ISSUE THREAD

**Issue by AntonioDiBella** [dronekit/dronekit-sitl#135]
Hello friends,
I have this problem with the dronekit execution. can someone help me?

pi@raspberrypi:~ $ dronekit-sitl copter
os: linux, apm: copter, release: stable
Downloading SITL from http://dronekit-assets.s3.amazonaws.com/sitl/copter/sitl-linux-copter-3.3.tar.gz
Download Complete.
Payload Extracted.
Ready to boot.
Traceback (most recent call last):
File "/home/pi/.local/bin/dronekit-sitl", line 10, in 
sys.exit(main())
File "/home/pi/.local/lib/python2.7/site-packages/dronekit_sitl/init.py", line 601, in main
sitl.launch(args, verbose=True)
File "/home/pi/.local/lib/python2.7/site-packages/dronekit_sitl/init.py", line 251, in launch
caps = ArdupilotCapabilities(self.path)
File "/home/pi/.local/lib/python2.7/site-packages/dronekit_sitl/init.py", line 160, in init
process = subprocess.Popen([path, '--help'], stdout=subprocess.PIPE)
File "/usr/lib/python2.7/subprocess.py", line 394, in init
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
raise child_exception
OSError: [Errno 8] Exec format error

**Comment by peterbarker** [comment]
On Thu, 4 Jul 2019, AntonioDiBella wrote:

> OSError: [Errno 8] Exec format error

Traditionally dronekit-sitl has only supported x86 - which a Pi is not.

I'm currently poking dronekit-sitl to work against our firmware servers, 
where we are not also compiling arm binaries.  This is a work in progress.

If you're willing to play around a bit you may be able to download 
arm-stil binaries from (e.g.) here: 
http://firmware.ardupilot.org/Copter/latest/SITL_arm_linux_gnueabihf/

and set the SITL_BINARY environment variable to point to that binary.

You'd probably be the first to do so :-)

Peter
