### ISSUE TITLE
Starting dronekit-sitl with no internet

### ISSUE THREAD

**Issue by alduxvm** [dronekit/dronekit-sitl#74]
Is there a way to start a dronekit-sitl instance without having internet?

When I don't have internet and try to do it, I get this error:

```
dronekit-sitl copter
os: osx, apm: copter, release: stable
Traceback (most recent call last):
  File "/usr/local/bin/dronekit-sitl", line 9, in <module>
    load_entry_point('dronekit-sitl==3.0.1', 'console_scripts', 'dronekit-sitl')()
  File "/usr/local/lib/python2.7/site-packages/dronekit_sitl/__init__.py", line 415, in main
    sitl.download(system, version, target=target, verbose=True)
  File "/usr/local/lib/python2.7/site-packages/dronekit_sitl/__init__.py", line 132, in download
    version = version_list()[system]['stable']
  File "/usr/local/lib/python2.7/site-packages/dronekit_sitl/__init__.py", line 83, in version_list
    raw = urllib2.urlopen(req).read()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1227, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>
```

**Comment by hamishwillee** [comment]
@alduxvm You need to download a vehicle for dronekit-sitl to start, and that requires the internet (above you are downloading "copter"). After you have downloaded an image the internet is no longer required. If you have already built a platform you can also point DK-Sitl to that to launch it.

So "yes", but you need to have internet for first use.

Closing!
