### ISSUE TITLE
Can't run SITL: JSON error

### ISSUE THREAD

**Issue by mtsakaguchi** [dronekit/dronekit-sitl#81]
Hello,

I am trying to get the dronekit-sitl up and running and am running into errors. I've tried installing from pip:
`pip install dronekit-sitl`
and from the github master:
`pip install git+https://github.com/dronekit/dronekit-sitl`

but when I install from github master and try running `dronekit-sitl --list` I get the error:
```

~$ dronekit-sitl --list
Traceback (most recent call last):
  File "/usr/local/bin/dronekit-sitl", line 9, in <module>
    load_entry_point('dronekit-sitl==3.0.1', 'console_scripts', 'dronekit-sitl')()
  File "/usr/local/lib/python2.7/dist-packages/dronekit_sitl/__init__.py", line 349, in main
    versions = version_list()
  File "/usr/local/lib/python2.7/dist-packages/dronekit_sitl/__init__.py", line 88, in version_list
    versions = json.loads(raw)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

and when I try and run `dronekit-sitl copter-3.3.0 --home=-35.363261, 149.165230, 584, 353` I get the error:

```
~$ dronekit-sitl copter-3.3.0 --home=-35.363261, 149.165230, 584, 353
os: linux, apm: copter, release: 3.3.0
Downloading SITL from http://dronekit-assets.s3.amazonaws.com/sitl/copter/sitl-linux-copter-3.3.0.tar.gz
Traceback (most recent call last):
  File "/usr/local/bin/dronekit-sitl", line 9, in <module>
    load_entry_point('dronekit-sitl==3.0.1', 'console_scripts', 'dronekit-sitl')()
  File "/usr/local/lib/python2.7/dist-packages/dronekit_sitl/__init__.py", line 422, in main
    sitl.download(system, version, target=target, verbose=True)
  File "/usr/local/lib/python2.7/dist-packages/dronekit_sitl/__init__.py", line 143, in download
    return download(system, version, target, verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/dronekit_sitl/__init__.py", line 111, in download
    testfile.retrieve(sitl_file, sitl_target + '/sitl.tar.gz')
  File "/usr/lib/python2.7/urllib.py", line 240, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 208, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 359, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 376, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 381, in http_error_default
    raise IOError, ('http error', errcode, errmsg, headers)
IOError: ('http error', 302, 'Moved Temporarily', <httplib.HTTPMessage instance at 0x7f3a0fab25a8>)
```
Note: I am behind a proxy which could possibly be why I'm getting the http error?

Any help would be appreciated

**Comment by eastmoutain** [comment]
hi, have you solved your problem?. i met the similar problem, the program is waiting for downloading "http://dronekit-assets.s3.amazonaws.com/sitl/copter/sitl-linux-copter-3.3.tar.gz", then i got the packet from internet by downloading it manually, but i don't know where should i install the packet.
